//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebooking.pg {
    
    
    public partial class dealerTab4CarShowModal {
        
        /// <summary>
        /// dealerTab4CarShowModalDivMarktype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivMarktype;
        
        /// <summary>
        /// dealerTab4CarShowModalDivMark control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivMark;
        
        /// <summary>
        /// dealerTab4CarShowModalDivSpec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivSpec;
        
        /// <summary>
        /// dealerTab4CarShowModalDivVinno control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivVinno;
        
        /// <summary>
        /// dealerTab4CarShowModalDivProducedyear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivProducedyear;
        
        /// <summary>
        /// dealerTab4CarShowModalDivFueltype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivFueltype;
        
        /// <summary>
        /// dealerTab4CarShowModalDivTransmissiontype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivTransmissiontype;
        
        /// <summary>
        /// dealerTab4CarShowModalDivZaalttype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivZaalttype;
        
        /// <summary>
        /// dealerTab4CarShowModalDivGetdt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivGetdt;
        
        /// <summary>
        /// dealerTab4CarShowModalDivPrice control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivPrice;
        
        /// <summary>
        /// dealerTab4CarShowModalDivExternalcolorname control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivExternalcolorname;
        
        /// <summary>
        /// dealerTab4CarShowModalDivInternalcolorname control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivInternalcolorname;
        
        /// <summary>
        /// dealerTab4CarShowModalDivExternalcolorcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivExternalcolorcode;
        
        /// <summary>
        /// dealerTab4CarShowModalDivInternalcolorcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalDivInternalcolorcode;
        
        /// <summary>
        /// dealerTab4CarShowModalModifyDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dealerTab4CarShowModalModifyDescription;
    }
}
