//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebooking.pg {
    
    
    public partial class service {
        
        /// <summary>
        /// serviceTab1SelectServiceType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect serviceTab1SelectServiceType;
        
        /// <summary>
        /// serviceTab3SelectServiceType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect serviceTab3SelectServiceType;
        
        /// <summary>
        /// serviceTab1ModalSelectServiceType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect serviceTab1ModalSelectServiceType;
        
        /// <summary>
        /// serviceTab1ModalExcelSelectServiceType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect serviceTab1ModalExcelSelectServiceType;
        
        /// <summary>
        /// serviceTab3ModalSelectServiceType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect serviceTab3ModalSelectServiceType;
        
        /// <summary>
        /// serviceTab3ModalSelectService control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect serviceTab3ModalSelectService;
        
        /// <summary>
        /// serviceTab3ModalInputBegindate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText serviceTab3ModalInputBegindate;
        
        /// <summary>
        /// serviceTab3ModalInputEnddate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText serviceTab3ModalInputEnddate;
        
        /// <summary>
        /// serviceTab3ModalInputPer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText serviceTab3ModalInputPer;
    }
}
